from ._typing import _VectBase

class _vectNSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEE(_VectBase[str]): ...
class _vectj(_VectBase[int]): ...
class _vectint(_VectBase[int]): ...
class _vecti(_VectBase[int]): ...
class _vectunsigned_int(_VectBase[int]): ...
