from typing_extensions import Literal

from ..ForceField import ForceField, MMFFMolProperties
from . import Mol

def GetUFFAngleBendParams(mol: Mol, idx1: int, idx2: int, idx3: int) -> None | tuple[float, float]: ...
def GetUFFBondStretchParams(mol: Mol, idx1: int, idx2: int) -> None | tuple[float, float]: ...
def GetUFFInversionParams(mol: Mol, idx1: int, idx2: int, idx3: int, idx4: int) -> None | float: ...
def GetUFFTorsionParams(mol: Mol, idx1: int, idx2: int, idx3: int, idx4: int) -> None | float: ...
def GetUFFVdWParams(mol: Mol, idx1: int, idx2: int) -> None | tuple[float, float]: ...
def MMFFGetMoleculeForceField(
    mol: Mol,
    pyMMFFMolProperties: MMFFMolProperties,
    nonBondedThresh: float = ...,
    confId: int = ...,
    ignoreInterfragInteractions: bool = ...,
) -> ForceField: ...
def MMFFGetMoleculeProperties(
    mol: Mol, mmffVariant: Literal["MMFF94", "MMFF94s"] = ..., mmffVerbosity: int = ...
) -> MMFFMolProperties: ...
def MMFFHasAllMoleculeParams(mol: Mol) -> bool: ...
def MMFFOptimizeMolecule(
    mol: Mol,
    mmffVariant: Literal["MMFF94", "MMFF94s"] = ...,
    maxIters: int = ...,
    nonBondedThresh: float = ...,
    confId: int = ...,
    ignoreInterfragInteractions: bool = ...,
) -> int: ...
def MMFFOptimizeMoleculeConfs(
    mol: Mol,
    numThreads: int = ...,
    maxIters: int = ...,
    mmffVariant: Literal["MMFF94", "MMFF94s"] = ...,
    nonBondedThresh: float = ...,
    ignoreInterfragInteractions: bool = ...,
) -> list[tuple[int, float]]: ...
def MMFFSanitizeMolecule(mol: Mol) -> int: ...
def OptimizeMolecule(ff: ForceField, maxIters: int = ...) -> int: ...
def OptimizeMoleculeConfs(mol: Mol, ff: ForceField, numThreads: int = ..., maxIters: int = ...) -> list[tuple[int, float]]: ...
def UFFGetMoleculeForceField(
    mol: Mol, vdwThresh: float = ..., confId: int = ..., ignoreInterfragInteractions: bool = ...
) -> ForceField: ...
def UFFHasAllMoleculeParams(mol: Mol) -> bool: ...
def UFFOptimizeMolecule(
    mol: Mol, maxIters: int = ..., vdwThresh: float = ..., confId: int = ..., ignoreInterfragInteractions: bool = ...
) -> int: ...
def UFFOptimizeMoleculeConfs(
    mol: Mol, numThreads: int = ..., maxIters: int = ..., vdwThresh: float = ..., ignoreInterfragInteractions: bool = ...
) -> list[tuple[int, float]]: ...
